### ISSUE TITLE
Pull down comment doesn't line up with code

### ISSUE THREAD

**Issue by MJuby** [UniversityOfPlymouth-Electronics/Embedded-Systems#8]
The comments next to the definition of BTN3_PIN & 4 say "No pull down" but when SW4 & 5 are called they are defined as PullDown.
![Capture](https://user-images.githubusercontent.com/72265042/96270868-16797f80-0fc4-11eb-9248-da43bcd54a7a.PNG)

**Comment by martin2100** [comment]
That's because there is no Pull Down resistors in the hardware so you have to specify to the Chip that the output circuitry of the chip needs to connect it's 'internal' resistor (actually a FET) so that the circuit will work and so the micro will  recognize a button press.
![image](https://user-images.githubusercontent.com/13520135/96272605-3ad65b80-0fc6-11eb-9037-939862ce4822.png)
